"""cmd: init — discover accounts from browser cookies and write the user-level config.

The user-level config (account registry + BOT space) is normally hand-copied from
`config.example.toml`; `init` derives it at runtime instead: enumerate the per-account
session cookies (`__Secure-pplx.session.<uid>`), probe `/api/auth/session` per token
for the email/display name, match the BOT space by title (optionally create it), and
write the TOML atomically with 0600 permissions. An existing file is never overwritten
without `--force`.

cmd: init——从浏览器 cookie 自动发现账户并生成用户级配置。

用户级配置（账户注册表 + BOT 空间）通常手工复制自 `config.example.toml`；`init`
改为运行时推导：枚举各账户会话 cookie（`__Secure-pplx.session.<uid>`），逐个探测
`/api/auth/session` 取 email/显示名，按标题匹配 BOT 空间（可选创建），再以 0600
权限原子写入 TOML。已存在的文件不加 `--force` 绝不覆盖。
"""

from __future__ import annotations

import json
import os
import re
import tempfile
from pathlib import Path

from ..config import DEFAULT_CONFIG_PATH, SESSION_URL
from ..core import cookies as ck
from ..core.logging import get_logger
from ..sites.perplexity.platform import API_VERSION

log = get_logger("cli")

LIST_COLLECTIONS_URL = ("https://www.perplexity.ai/rest/collections/list_user_collections"
                        f"?version={API_VERSION}&source=default")
# Title shared by BOT-space matching and --create-bot-space creation
# 匹配既有 BOT 空间与 --create-bot-space 创建共用的标题
BOT_TITLE = "BOT"


def _enumerate_tokens(cookies_from: str | None, cookies_file: str | None) -> dict[str, tuple[str, str]]:
    """Enumerate per-account session tokens: {user_id: (token, source)}.

    From the browser stores by default; a cookie file is scanned for
    `__Secure-pplx.session.<uid>` entries instead (a full export may carry several
    accounts).

    枚举各账户会话令牌：{user_id: (token, 来源)}。

    默认读浏览器库；指定 cookie 文件时改扫文件内的 `__Secure-pplx.session.<uid>` 条目
    （完整导出可能携带多个账户）。
    """
    if cookies_file:
        cdict = ck.from_file(cookies_file)
        return {n[len(ck.ACCOUNT_SESSION_PREFIX):]: (v, f"file:{cookies_file}")
                for n, v in cdict.items() if n.startswith(ck.ACCOUNT_SESSION_PREFIX)}
    browsers = [cookies_from] if cookies_from else None
    return ck.list_account_tokens(browsers)


def _session_user(sess: dict) -> tuple[str, str]:
    """Extract (email, display name) from an /api/auth/session response.

    从 /api/auth/session 响应提取（email, 显示名）。
    """
    user = (sess or {}).get("user") or {}
    return user.get("email") or "", user.get("name") or ""


def _name_key(email: str, uid: str, taken: set[str]) -> str:
    """Derive a unique registry key from the email local part (uid fallback), suffixing
    -2/-3/… on collision.

    由 email 本地部分派生唯一注册键（无 email 用 uid 兜底），撞名时加 -2/-3/… 后缀。
    """
    base = email.split("@")[0] if email else f"account-{uid[:8]}"
    base = re.sub(r"[^a-z0-9_-]+", "-", base.lower()).strip("-") or "account"
    key, i = base, 2
    while key in taken:
        key = f"{base}-{i}"
        i += 1
    taken.add(key)
    return key


def find_bot_space(items: list[dict], title: str = BOT_TITLE) -> tuple[str, str]:
    """Match a space by exact title (case-insensitive) in a list_user_collections
    payload; returns (uuid, slug) or ("", "").

    在 list_user_collections 负载中按标题精确匹配（大小写不敏感）空间；
    返回 (uuid, slug) 或 ("", "")。
    """
    for c in items:
        if str(c.get("title", "")).strip().lower() == title.lower():
            return str(c.get("uuid") or ""), str(c.get("slug") or "")
    return "", ""


def _toml_str(v: str) -> str:
    """Escape a value for a TOML basic string.

    转义 TOML 基本字符串值。
    """
    return '"' + v.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_config(accounts: dict[str, dict], default_account: str,
                  bot_uuid: str, bot_slug: str) -> str:
    """Render the user-level config TOML (accounts + BOT space).

    渲染用户级配置 TOML（账户 + BOT 空间）。
    """
    lines = [
        "# Generated by `pplx-export init` — personal identity data; keep owner-only (chmod 600).",
        "# 由 `pplx-export init` 生成——个人身份数据，请保持 0600 权限。",
        "",
        f"default_account = {_toml_str(default_account)}",
        "",
    ]
    for key in sorted(accounts):
        a = accounts[key]
        lines += [
            f"[accounts.{key}]",
            f"display_name = {_toml_str(a['display_name'])}",
            f"email = {_toml_str(a['email'])}",
            f"user_id = {_toml_str(a['user_id'])}",
            "",
        ]
    lines += [
        "# BOT space: where threads created by pplx-ask are collected after completion",
        "# (create one via `pplx-ask space-create` or `pplx-export init --create-bot-space`)",
        "# BOT 空间：pplx-ask 发问完成后线程的集中收纳处",
        "#（可经 `pplx-ask space-create` 或 `pplx-export init --create-bot-space` 实建）",
        "[bot_space]",
        f"uuid = {_toml_str(bot_uuid)}",
        f"slug = {_toml_str(bot_slug)}",
        "",
    ]
    return "\n".join(lines)


def write_config(path: Path, text: str, *, force: bool = False) -> Path:
    """Write the config atomically with 0600 permissions; refuse to overwrite an
    existing file unless force.

    以 0600 权限原子写入配置；已存在时不加 force 拒绝覆盖。
    """
    if path.exists() and not force:
        raise SystemExit(f"[init][ERROR] {path} 已存在——检查后手工编辑，或加 --force 覆盖")
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=str(path.parent), prefix=".config-", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(text)
        os.chmod(tmp, 0o600)
        os.replace(tmp, path)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise
    return path


def cmd_init(args, *, transport_factory=None, create_space_fn=None):
    """Discover accounts from cookies and write the user-level config.

    transport_factory / create_space_fn are injection points for tests; the defaults
    build a CookieTransport per probe and call ask_api.create_space.

    从 cookie 发现账户并写入用户级配置。

    transport_factory / create_space_fn 为测试注入点；默认每次探测新建
    CookieTransport，创建空间调 ask_api.create_space。
    """
    from ..core.http.cookie_transport import CookieTransport
    from ..sites.perplexity.ask_api import create_space as _create_space

    if getattr(args, "transport", "cookie") == "webbridge":
        raise SystemExit("[init][ERROR] init 只走 cookie 通路（webbridge 页面上下文无法枚举账户令牌）")
    out_path = Path(args.config).expanduser() if args.config else DEFAULT_CONFIG_PATH
    # The default factory binds `source` lazily (assigned by ck.resolve below, before
    # the first probe) so init probes carry the same source-derived UA
    # 默认工厂惰性绑定 `source`（由下方 ck.resolve 赋值，首次探测前已就绪），
    # 让 init 探测携带同样的来源派生 UA
    tf = transport_factory or (lambda cdict: CookieTransport(cdict, source=source))

    # 1. Cookies
    # 1. cookie 获取
    try:
        base, source = ck.resolve(cookies_from=args.cookies_from, cookies_file=args.cookies,
                                  cache_path=(Path(args.out) / "index" / ".cookies.json"))
    except Exception as e:
        raise SystemExit(f"[init][ERROR] cookie 获取失败：{e}\n"
                         f"  请先在浏览器登录 Perplexity，或用 --cookies-from/--cookies 指定来源。")
    log.info(f"[init] cookie 来源: {source}")

    # 2. Probe every per-account token; fall back to the active session alone
    # 2. 逐账户令牌探测；无枚举结果时退化为仅探测当前会话
    tokens = _enumerate_tokens(args.cookies_from, args.cookies)
    probed: list[dict] = []
    candidates = sorted(tokens.items()) if tokens else [("", (base.get(ck.ACTIVE_SESSION_COOKIE, ""), source))]
    for uid, (token, src) in candidates:
        cdict = dict(base)
        if token:
            cdict[ck.ACTIVE_SESSION_COOKIE] = token
        try:
            sess = tf(cdict).get_json(SESSION_URL, timeout=20)
        except Exception as e:
            log.warning(f"[init] 账户令牌 {(uid or '(active)')[:8]} 探测失败（可能已过期），跳过: {e}")
            continue
        email, name = _session_user(sess)
        if not email:
            log.warning(f"[init] 账户令牌 {(uid or '(active)')[:8]} 探测未得 email，跳过")
            continue
        probed.append({"uid": uid, "email": email, "name": name})
        log.info(f"[init] 发现账户: {email}（{src}）")
    if not probed:
        raise SystemExit("[init][ERROR] 未探测到任何账户——请确认浏览器已登录 Perplexity 后重试")

    # 3. Assemble the registry; default = the currently active account (else first)
    # 3. 装配注册表；default = 当前生效账户（否则取第一个）
    try:
        cur_email, _ = _session_user(tf(base).get_json(SESSION_URL, timeout=20))
    except Exception:
        cur_email = ""
    taken: set[str] = set()
    accounts: dict[str, dict] = {}
    key_by_email: dict[str, str] = {}
    for p in probed:
        key = _name_key(p["email"], p["uid"], taken)
        accounts[key] = {"display_name": p["name"] or p["email"],
                         "email": p["email"], "user_id": p["uid"]}
        key_by_email[p["email"].lower()] = key
    default = key_by_email.get(cur_email.lower(), sorted(accounts)[0])

    # 4. BOT space: match by title, optionally create. --create-bot-space may carry
    # an explicit title, which then drives both matching and creation.
    # 4. BOT 空间：按标题匹配，可选创建。--create-bot-space 可附显式标题，
    # 此时匹配与创建均使用该标题。
    bot_uuid = bot_slug = ""
    bot_title = getattr(args, "bot_title", None) or BOT_TITLE
    cbs = getattr(args, "create_bot_space", None)
    create_title: str | None = None
    if isinstance(cbs, str):
        # argparse: bare flag → "" (create with --bot-title); explicit title → use it
        # argparse：裸标志 → ""（按 --bot-title 创建）；显式标题 → 用之
        create_title = cbs.strip() or bot_title
    elif cbs:
        # Truthy non-string flag (programmatic callers) → create with --bot-title
        # 非字符串真值标志（编程调用方）→ 按 --bot-title 创建
        create_title = bot_title
    match_title = create_title or bot_title
    try:
        j = tf(base).get_json(LIST_COLLECTIONS_URL, timeout=30)
        items = j if isinstance(j, list) else (j.get("collections") or j.get("items") or [])
        bot_uuid, bot_slug = find_bot_space(items, match_title)
    except Exception as e:
        log.warning(f"[init] 空间列表获取失败: {e}")
    if bot_uuid:
        log.info(f"[init] 匹配到 BOT 空间（{bot_uuid[:8]}）")
    elif create_title:
        creator = create_space_fn or _create_space
        r = creator(tf(base), create_title)
        bot_uuid, bot_slug = str(r.get("uuid") or ""), str(r.get("slug") or "")
        log.info(f"[init] 已创建 BOT 空间「{create_title}」（{bot_uuid[:8]}）")
    else:
        log.warning(f"[init] 未找到标题为 {match_title} 的空间——bot_space 留空（pplx-ask 完成后线程留在原处）；"
                    "可 --bot-title 指定既有空间标题、--create-bot-space [标题] 创建，或稍后手工填写")

    # 5. Write atomically
    # 5. 原子写入
    write_config(out_path, render_config(accounts, default, bot_uuid, bot_slug),
                 force=args.force)
    log.info(f"[init] 已写入 {out_path}（0600）：{len(accounts)} 个账户，default={default}"
             + (f"，BOT={bot_uuid[:8]}" if bot_uuid else ""))

    # Seed the [models] table best-effort so a fresh config already carries current
    # model defaults/catalog (refreshable later via `pplx-ask models --refresh`).
    # best-effort 播种 [models]，让新配置即带当前模型默认/目录（后续可 `pplx-ask models --refresh`）。
    try:
        from ..sites.perplexity.ask_api import refresh_models
        section = refresh_models(tf(base), out_path)
        log.info(f"[init] 已播种 [models]（{len(section.get('catalog') or {})} 模型，"
                 f"last_refreshed={section.get('last_refreshed')}）")
    except Exception as e:
        log.warning(f"[init] [models] 播种跳过（可稍后 `pplx-ask models --refresh`）: {e}")

    print(json.dumps({"config": str(out_path), "accounts": sorted(accounts),
                      "default_account": default,
                      "bot_space_uuid": bot_uuid, "bot_space_slug": bot_slug},
                     ensure_ascii=False))
